kind: Deployment
apiVersion: apps/v1
metadata:
  name: quarkus-example
  namespace: quarkus-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-example
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: quarkus-example
    spec:
      containers:
        - name: quarkus-example
          image: 'quay.io/sscaling/quarkus-example:latest'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
